name: Build and Upload Pump

on:
  push:
    paths:
      - 'tootls/pump/**'  # Theo dõi các thay đổi trong thư mục tootls/pump

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run PowerShell script
        run: |
          $ErrorActionPreference = 'Stop'
          $workdir = "D:\a\Stealer_vietnam\Stealer_vietnam"
          & powershell -ExecutionPolicy Bypass -File "$workdir\tootls\pump\buildcode.dontcare"

      - name: Upload pump.exe
        uses: actions/upload-artifact@v3
        with:
          name: pump
          path: tootls/pump/pump.exe
