name: Build and Upload Pump

on:
  push:
    paths:
      - 'tootls/pump/**'  # Theo dõi các thay đổi trong thư mục tootls/pump

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run PowerShell script
        run: |
          $ErrorActionPreference = 'Stop'
          $workdir = "D:\a\Stealer_vietnam\Stealer_vietnam"
          & powershell -ExecutionPolicy Bypass -File "$workdir\tootls\pump\buildcode.ps1"

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .\tootls\pump\pump.exe
          git commit -m "Upload pump.exe file"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
